# -*- coding: utf-8 -*-
"""Avneesh_project2_Financial Market News Sentiment Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_gwHmfl6JpUbOev_Wr83u-EdhfIPl4R

Financial Market News Sentiment Analysis

Objective  - Sentiment analysis on natural language sentences can increase the accuracy of market prediction because financial markets are influenced by investor sentiments.

Data Source - Ybi Foundation Dataset (https://github.com/YBI-Foundation/Dataset/blob/main/Financial%20Market%20News.csv)

Import Library
"""

import pandas as pd

import numpy as np

import sklearn

"""Import Data"""

df = pd.read_csv("https://github.com/YBI-Foundation/Dataset/raw/main/Financial%20Market%20News.csv",encoding ="ISO-8859-1")

df.head()

"""Describe Data"""

df.info

df.describe()

"""Data Visualization"""

df.shape

df.columns

"""Get Feature Selection"""

' '.join(str(x) for x in df.iloc[1,2:27])

df.index

len(df.index)

"""Data Preprocessing"""

news = []
for row in range(0,len(df.index)):
  news.append(' '.join(str(x) for x in df.iloc[1,2:27]))

type(news)

news[0]

x = news

type(x)

"""Get Feature Text Conversion to bag of Words"""

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase = True,ngram_range=(1,1))

"""Define Target Variable (y) and Feature Variables (X)"""

x = cv.fit_transform(x)

x.shape

y = df['Label']

y.shape

"""Train Test Split"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size = 0.3,stratify = y,random_state = 2529)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators = 200)

rf.fit(x_train,y_train)

y_pred = rf.predict(x_test)

from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

confusion_matrix(y_test, y_pred)

print(classification_report(y_test,y_pred))